FROM mcr.microsoft.com/windows/servercore:1809

RUN ["powershell", "Set-ExecutionPolicy", "Bypass", "-Scope", "Process", "-Force;"]
RUN ["powershell", "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"]

RUN choco install git.install -yf

# Consul K8s constrol plane version
ARG K8S_CONTROL_PLANE_CONSUL_VERSION=1.0.0

RUN curl -sSL "https://releases.hashicorp.com/consul-k8s-control-plane/%K8S_CONTROL_PLANE_CONSUL_VERSION%/consul-k8s-control-plane_%K8S_CONTROL_PLANE_CONSUL_VERSION%_windows_amd64.zip" \
    -o consul-k8s-control-plane.zip
RUN mkdir consul-k8s-control-plane
RUN tar -xf consul-k8s-control-plane.zip -C consul-k8s-control-plane

# Set Path
RUN SETX /M path "%PATH%;C:\consul-k8s-control-plane;C:\Program Files\Git\bin;"

SHELL [ "bash.exe" ]
ENTRYPOINT ["consul-k8s-control-plane.exe"]
